version: "3.5"
services:
  manager:
    container_name: manager___
    build:
      context: ./manager
      dockerfile: Dockerfile
    hostname: manager
    ports:
      - "8000:8000"
    networks:
      - crack-hash-network
  worker0:
    container_name: worker0___
    build:
      context: ./worker
      dockerfile: Dockerfile
    hostname: worker0
    ports:
      - "8080:8080"
    networks:
      - crack-hash-network
  worker1:
    container_name: worker1___
    build:
      context: ./worker
      dockerfile: Dockerfile
    hostname: worker1
    ports:
      - "8081:8080"
    networks:
      - crack-hash-network
  worker2:
    container_name: worker2___
    build:
      context: ./worker
      dockerfile: Dockerfile
    hostname: worker2
    ports:
      - "8082:8080"
    networks:
      - crack-hash-network
  worker3:
    container_name: worker3___
    build:
      context: ./worker
      dockerfile: Dockerfile
    hostname: worker3
    ports:
      - "8083:8080"
    networks:
      - crack-hash-network

networks:
  crack-hash-network:
    driver: bridge
